# generateLAESIImage: This script takes in the merged matrix generated by xlsToMatrix.R as well as the mz of interest. Using the Cardinal package (developer version),  a MSImageSet object is generated. Ion intensity maps are then generated using this object
# Input: file path (*.xlsx), total number of sheets
# Output: Data cube as a data.frame object
#Author: Purva Kulkarni
#Date: 13 October 2016

#######################################################################################################

# Install Cardinal if not installed
# source("https://bioconductor.org/biocLite.R")
# biocLite("Cardinal")

library(Cardinal)
library(viridis)

options(java.parameters = "-Xmx4g")
library(openxlsx) # Very fast for reading large xlsx files

generateLAESIImage <- function(path, mzListpath, ncol, nrow, mzValue, main)
{
  # Read the *.xls file containing the data cube
  matrixData <- read.xlsx(path, colNames = TRUE)
  matrixData <- matrixData[,-1]
  
  # Read the *.xls file containing the mzList
  mzList <- read.xlsx(mzListpath, colNames = TRUE)
  
  # Create a MSImageSet object using the Cardinal package
  msset <- MSImageSet(matrixData, mzList, coord = expand.grid(x=1:nrow, y=1:ncol))
  
  # Create the viridis color gradient
  mycol <- viridis(100)
  
  # View the ion intensity map over the full mass range
  image(msset, feature = 1:length(mzList), col.regions = mycol, plusminus = 0.1, main)
  
  # View the ion intensity map of a paricular mzValue of interest
  image(msset, mz = mzValue, col.regions = mycol, plusminus = 0.1, main)
}
